components:
  schema:
    mainImages:
      type: object
      properties:
        status:
          type: number
        statusText:
          type: string
        request:
          type: object
          properties:
            url:
              type: string
            method:
              type: string
            headers:
              type: object
              properties:
                host:
                  type: string
                accept:
                  type: string
                params:
                  type: string
                query:
                  type: string
        data:
          type: object
          properties:
            img_url:
              type: string